name: Run Flix tests

on:
  push:
    paths:
      - "2022-flix/"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "flix/flix"
          tag: "v0.34.0"
          fileName: "flix.jar"
          out-file-path: "./2022-flix"
      - name: Run tests
        working-directory: ./2022-flix
        run: java -jar flix.jar test
